### ISSUE TITLE
Words with Polish characters show as misspelled

### ISSUE THREAD

**Issue by jameskentTX** [atom/spell-check#266] opened 2018-08-28 08:13 UTC
Words without Polish characters like "powoli", "szybko" are ok, but well known and popular words with Polish characters ("ą", "ę", "ł", "ó", "ś", "ż", "ź"), like "użytkownik" (user), "pisać" (write), are marked as mispelled.

I'm working on Debian, I have hunspell and polish dictionary installed. Spell-check is properly configured (locales: en-US, pl-PL, locale paths: /usr/share/hunspell). In /usr/share/hunspell directory there are files like: pl_PL.dic, pl_PL.aff, en_US.dic, en_US.aff)

**Comment by korneliakobiela** [comment] 2018-10-15 20:00
I have the same issue on ubuntu 18.04

**Comment by by-cx** [comment] 2018-10-16 10:17
Same problem with Czech :-(

I am on Ubuntu 16.04 and I use hunspell from its repo.

**Comment by Whitie** [comment] 2018-11-13 08:32
Same problem with german umlauts on Arch Linux.

**Comment by palant** [comment] 2018-11-30 10:59
This might be a duplicate of #241.

**Comment by dmoonfire** [comment] 2019-01-14 18:06
Duplicate of #241.

**Closed by dmoonfire** 2019-01-14 18:06 UTC
