### ISSUE TITLE
not working at all with atom 1.7.3 on Debian jessie

### ISSUE THREAD

**Issue by byterazor** [atom/spell-check#138] opened 2016-05-10 19:36 UTC
Hi,

i can not get spell-check working at all on Debian Jessie. I remove the .atom directory, started
atom and tried to edit files: test, test.txt . In none of them spell-checking occured.

**Comment by sumdog** [comment] 2016-05-10 23:45
I have the same issue with atom-1.7.3 on Gentoo (from the standard Gentoo Portage). It was working on 1.7.2. I've checked my settings and ensured my scope is correct (source.gfm). 

Where is the logging for this? Is there a way to diagnose the issue?

**Comment by sleepyfox** [comment] 2016-05-12 14:24
I have the same issue on Linux Mint stable with Atom 1.7.3

**Comment by arnaudporet** [comment] 2016-05-17 13:24
Same thing under Arch Linux (Atom 1.7.3 from AUR).

**Comment by kachkaev** [comment] 2016-05-24 11:31
Same thing on Ubuntu 16.04 (Atom 1.7.3). Clicked through all possible settings, read all I could find on the web but then had to give up :-)

**Comment by 50Wliu** [comment] 2016-05-24 11:52
Tentatively closing as a duplicate of #129 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-24 11:52 UTC

**Comment by sleepyfox** [comment] 2016-05-24 14:42
@50Wliu I would think twice before taking a well understood verified issue and marking it as a duplicate of another issue that is marked "needs-reproduction" and "more-info-needed"...

**Comment by 50Wliu** [comment] 2016-05-24 19:51
This issue is 1) not well understood (in fact none of the comments specify whether Atom was launched in safe mode or not), 2) even more vague than the linked issue, as it does not provide any repro steps or workarounds, and 3) not verified as it didn't have any labels on it.

Until there is sufficient evidence that this issue is different from #129 I'm going to keep this one mashed as a duplicate.

**Comment by sumdog** [comment] 2016-05-24 20:34
I agree, #129 is a duplicate of this issue. After viewing that issue, I was able to get my spellcheck working again.
