### ISSUE TITLE
Cannot load en-CA

### ISSUE THREAD

**Issue by cmanage1** [atom/spell-check#335] opened 2020-05-15 19:59 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1.  Open Atom

**Expected behavior:**

 

**Actual behavior:**

 Error in yellow window "Cannot load the checker for en-XX" 

**Reproduces how often:**

 Every time Atom is opened

### Additional Information
Running Atom on macOS Catalina 10.15.4

![Screen Shot 2020-05-15 at 4 03 27 PM](https://user-images.githubusercontent.com/55030581/82091621-af2e6b00-96c5-11ea-8ec8-19270bc3b58d.png)

**Comment by dmoonfire** [comment] 2020-05-18 06:12
Duplicate of https://github.com/atom/spell-check/issues/328.

**Closed by dmoonfire** 2020-05-18 06:12 UTC
