### ISSUE TITLE
Spell check doesn't work on mac

### ISSUE THREAD

**Issue by lirlex** [atom/spell-check#113] opened 2016-02-13 19:23 UTC
sw_vers -productVersion 
10.11.3

atom --version
1.5.3

apm list --installed 
/Users/alexei/.atom/packages (0)
└── (empty)

<img width="653" alt="screen shot 2016-02-13 at 9 21 52 pm" src="https://cloud.githubusercontent.com/assets/14213598/13029535/dbddea28-d297-11e5-921e-dffd171823e9.png">

<img width="814" alt="screen shot 2016-02-13 at 9 18 15 pm" src="https://cloud.githubusercontent.com/assets/14213598/13029513/70dfeff0-d297-11e5-8c92-dca56c36b8fe.png">

**Comment by lee-dohm** [comment] 2016-02-18 22:58
The spell-check package works in plain text out-of-the-box without needing to change the grammar settings.

Just verified using Atom v1.7.0-dev-e060ccb on Mac OS X 10.11.3:

<img width="636" alt="screen shot 2016-02-18 at 2 56 17 pm" src="https://cloud.githubusercontent.com/assets/1038121/13161021/f70e62da-d64f-11e5-93de-0702871a2310.png">

Please let us know if there is any other information you can share as to what might be going wrong!

**Comment by johnchristopherjones** [comment] 2016-03-04 19:07
I'm running Stable (1.5.4) and Beta (1.6.0-beta6) on OS X 10.11.3 and seeing the same lack of spell check as @lirlex.  Perhaps the spell check package only works with the dev channel?

**Comment by lee-dohm** [comment] 2016-03-04 23:03
Nope, spell check works even on the Stable version:

<img width="541" alt="screen shot 2016-03-04 at 3 02 37 pm" src="https://cloud.githubusercontent.com/assets/1038121/13542792/42c4b758-e21a-11e5-849e-cc6adedf4d1c.png">

Tested using Atom v1.5.4 on Mac OS X 10.11.3.

**Comment by johnchristopherjones** [comment] 2016-03-05 18:20
In my case I think it might be an interaction with a CSV package.  The problem appears to be intermittent and perhaps related to whether a CSV package is loaded at the time.  I'm having trouble reproducing it today.  Not sure if this is the same problem reported by @lirlex.

**Comment by D34D10CK** [comment] 2016-03-22 10:03
I had the same issue on Windows, the problem was that you have to have the en_us locale installed otherwise the spellchecker module doesn't work. Maybe this is a similar issue?

**Comment by lee-dohm** [comment] 2016-03-22 22:24
That sounds like it could be a good explanation. @lirlex and @johnchristopherjones ... does @D34D10CK's explanation sound like it might be the issue?

**Comment by lirlex** [comment] 2016-03-22 22:35
Sorry for long delay.
I didn't change locale when experienced this problem. But now I can't reproduce issue anymore on same version.

**Comment by lee-dohm** [comment] 2016-03-22 22:38
Thanks for getting back to us @lirlex. Since it appears nobody is actively experiencing this right now, I'm going to close this. Please let us know if it reoccurs!

**Closed by lee-dohm** 2016-03-22 22:38 UTC
Labels: more-information-needed

**Comment by dcitllc** [comment] 2017-05-24 15:23
I can't seem to get spell check to work on my Mac either. I'm using MAC Sierra.

**Comment by stefanocoretta** [comment] 2020-03-27 08:15
Same problem here, the package suddently stopped working.

```
atom 1.45.0
spell-check 0.75.0
macOS 10.15.3 (19D76)
```

```
apm list
Built-in Atom Packages (93)
├── atom-dark-syntax@0.29.1
├── atom-dark-ui@0.53.3
├── atom-light-syntax@0.29.1
├── atom-light-ui@0.46.3
├── base16-tomorrow-dark-theme@1.6.0
├── base16-tomorrow-light-theme@1.6.0
├── one-dark-ui@1.12.5
├── one-light-ui@1.12.5
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.3.0
├── solarized-light-syntax@1.3.0
├── about@1.9.1
├── archive-view@0.65.1
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.8
├── autocomplete-plus@2.42.3
├── autocomplete-snippets@1.12.1
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0 (disabled)
├── bookmarks@0.46.0
├── bracket-matcher@0.91.2
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.219.1
├── fuzzy-finder@1.14.1
├── github@0.34.0
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.64.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.39.0
├── line-ending-selector@0.7.7
├── link@0.31.6
├── markdown-preview@0.160.2
├── metrics@1.8.1
├── notifications@0.71.0
├── open-on-github@1.3.2
├── package-generator@1.3.0
├── settings-view@0.261.3
├── snippets@1.5.0
├── spell-check@0.75.0
├── status-bar@1.8.17
├── styleguide@0.49.12
├── symbols-view@0.118.2
├── tabs@0.110.0
├── timecop@0.36.2
├── tree-view@0.228.0
├── update-package-dependencies@0.13.1
├── welcome@0.36.9
├── whitespace@0.37.7
├── wrap-guide@0.41.0
├── language-c@0.60.18
├── language-clojure@0.22.8
├── language-coffee-script@0.50.0
├── language-csharp@1.1.0
├── language-css@0.44.2
├── language-gfm@0.90.7 (disabled)
├── language-git@0.19.1
├── language-go@0.47.1
├── language-html@0.53.0
├── language-hyperlink@0.17.1
├── language-java@0.31.4
├── language-javascript@0.134.0
├── language-json@1.0.4
├── language-less@0.34.3
├── language-make@0.23.0
├── language-mustache@0.14.5
├── language-objective-c@0.16.0
├── language-perl@0.38.1
├── language-php@0.44.4
├── language-property-list@0.9.1
├── language-python@0.53.3
├── language-ruby@0.72.22
├── language-ruby-on-rails@0.25.3
├── language-rust-bundled@0.1.0
├── language-sass@0.62.1
├── language-shellscript@0.28.0
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.20.0
├── language-typescript@0.6.0
├── language-xml@0.35.3
└── language-yaml@0.32.0

Dev Packages (1) /Users/stefano/.atom/dev/packages
└── language-praat@1.4.0

Community Packages (33) /Users/stefano/.atom/packages
├── Zen-plus@1.1.0
├── atom-css-clean@2.24.1 (disabled)
├── atom-ide-ui@0.13.0 (disabled)
├── atom-language-r@1.4.8
├── autocomplete-awk@0.1.2
├── autocomplete-bibtex@1.2.7 (disabled)
├── color-picker@2.3.0 (disabled)
├── document-outline@2.1.2
├── file-icons@2.1.39
├── ide-css@0.3.3 (disabled)
├── ide-html@0.6.0 (disabled)
├── ide-json@0.2.1 (disabled)
├── ide-yaml@0.7.0 (disabled)
├── insert-timestamp@0.2.4
├── language-awk@0.1.12
├── language-hugo@0.5.1 (disabled)
├── language-latex@1.2.0
├── language-literate@0.13.0
├── language-markdown@0.37.0
├── language-matlab@0.2.1
├── language-praat@1.4.0
├── latex@0.50.2
├── latex-tree@0.5.0
├── magic-reflow@0.3.0
├── minimap@4.29.9
├── one-o-eight-syntax@0.39.0
├── rainbow-csv@1.0.0
├── remote-edit-ni@3.6.0
├── scroll-sync@0.2.4
├── sync-settings@4.3.2
├── teletype@0.13.4 (disabled)
├── todo@0.6.0
└── wordcount@3.1.0
```
