### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by healthy-tree** [atom/spell-check#263] opened 2018-07-26 01:38 UTC
### Description

Just open Atom,  the following error will appear：

```
Cannot load the system dictionary for zh-CN. Checked the following paths for dictionary files:
/
/System/Library/Spelling
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/spellchecker/vendor/hu
```

### Steps to Reproduce

... ...

### Versions

1. Atom Version

Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

2. apm Version

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 2.7.15
git 2.17.0

**Comment by rsese** [comment] 2018-07-26 22:40
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/spell-check/issues/253 (see https://github.com/atom/spell-check/issues/253#issuecomment-404318992 in particular) so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-07-26 22:40 UTC
