### ISSUE TITLE
Shortcut to go to previous (next) error

### ISSUE THREAD

**Issue by jefferyyuan** [atom/spell-check#308] opened 2019-06-05 08:09 UTC
- Usually when we are typing, we find some misspelling before, now we have to move cursor to the previous misspelled word to fix it.
- For people who don't use mouse, or trackpad, this is kind of pain.
- It would be we can use shortcut to quickly go to previous(next) error.

**Comment by rsese** [comment] 2019-06-05 17:47
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/spell-check/issues/208 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-05 17:47 UTC
