### ISSUE TITLE
No sign of warnings (Linux)

### ISSUE THREAD

**Issue by diraimondo** [atom/spell-check#134] opened 2016-04-27 13:12 UTC
I've started to used Atom (1.7.2 in ArchLinux by AUR) since some weeks. I got all I need for C developing and LaTeX writing. All I miss is a working spell-check (at least for English). 
I've read about issue #129 but my issue looks different: I can't make it work even changing my LANG environment variable. I've tested it with Markdown files and also with LaTeX documents (adding specific scope to the settings).

```
$ atom -v
Atom    : 1.7.2
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ pacman -Q | grep hunspell
hunspell 1.3.4-1
hunspell-en 2016.01.19-1
hunspell-it 2.4-4

$ echo $LANG
it_IT.utf8

$ export LANG=en_US.UTF-8
$ echo $LANG
en_US.UTF-8

$ rm -rf ~/.atom/  # no relation to other add-ons or settings

$ atom -f /tmp/test-atom/test.md 
[10373:0427/150814:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[10373:0427/150814:ERROR:browser_main_loop.cc(253)] Gtk: Locale not supported by C library.
        Using the fallback 'C' locale.
App load time: 538ms
[10373:0427/150815:INFO:CONSOLE(52)] "Window load time: 629ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (52)
[10373:0427/150816:INFO:CONSOLE(47)] "No deserializer found for", source: /usr/share/atom/resources/app.asar/src/deserializer-manager.js (47)
[10373:0427/150817:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[10373:0427/150817:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
^C
### no spell-checking warning...

$ export LANG=
$ echo $LANG

$ atom -f /tmp/test-atom/test.md
[10687:0427/151013:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 571ms
[10687:0427/151015:INFO:CONSOLE(52)] "Window load time: 511ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (52)
[10687:0427/151015:INFO:CONSOLE(47)] "No deserializer found for", source: /usr/share/atom/resources/app.asar/src/deserializer-manager.js (47)
[10687:0427/151015:INFO:CONSOLE(47)] "No deserializer found for", source: /usr/share/atom/resources/app.asar/src/deserializer-manager.js (47)
[10687:0427/151016:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[10687:0427/151016:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
^C

### nothing here too....
```

**Comment by diraimondo** [comment] 2016-04-28 08:44
@lee-dohm tell how can I help you. All the details of my system are in my opening report. I can make all the tests that you suggest. It could be useful if there is any kind of low-level log/debug functionality in Atom subsystem (I was not able to find it).

More details: I've tried to revert the patch that uses the environment variable LANG as suggested in https://github.com/atom/spell-check/issues/129#issuecomment-214789767 but it didn't help. It looks not related to the language selection mechanism: a problem to find or bind the hunspell library?

**Comment by tumido** [comment] 2016-04-28 18:49
I'm facing the same on both `Fedora` and `Arch`.

Following GIF was created on a completely clean setup (default `.atom` settings):
![spell_check](https://cloud.githubusercontent.com/assets/7453394/14897212/680815f4-0d81-11e6-8a94-b8eb3a0c9bee.gif)

As you can see no console output for any spell checker failure and no misspelled words are detected.
It seems the spell checker was not even initiated.

**Comment by lee-dohm** [comment] 2016-04-28 21:14
I strongly suspect that this is a duplicate of #129, despite the difference in behavior from the environment variables.

**Comment by diraimondo** [comment] 2016-04-29 08:09
@lee-dohm it could be but all the workarounds (env. variable and patch revert) working there are not useful here...
Any way to debug?

**Comment by tumido** [comment] 2016-04-29 12:28
Well, as I can see now `spell-check` starts working on my Fedora once I've switched to the precompiled RPM package from [Atom.io](atom.io) site. This means the problem can probably be in some unspecified regression between `node.js` packages and Atom or Electron core. `node.js` being linked statically (precompilled pkg) or dynamically (my previously used build) is the only difference between those builds.

**Comment by sashasimkin** [comment] 2016-05-01 16:56
_Disclaimer: I could just press +1, but there's a label `needs-reproduction`, so I'm going to post my story_
So, I'm using fedora 23, have installed atom using instructions from `https://copr.fedorainfracloud.org/coprs/mosquito/atom/`, section `- Update node.js for fc23 and el7`
This gave me:
> $ atom -v
Atom    : 1.7.2
Electron: 0.37.7
Chrome  : 49.0.2623.75
Node    : 5.10.0

With this setup symptoms were exactly the same as @tumido faced. I've also read #129 and tried listed workarounds, which didn't help. After that, I went to [http://atom.io](atom.io) and downloaded proposed `.rpm`, after installation I've got:
> $ atom -v
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

And now spell checking works (At least I can see red dotted underline beneath misspelled words).

P.s: I haven't been cleaning `.atom` folder, so the packages and the rest left the same as was.

**Comment by 50Wliu** [comment] 2016-05-01 16:57
@diraimondo Are you also using the mosquito COPR repo?

**Comment by diraimondo** [comment] 2016-05-02 07:35
@50Wliu I'm on ArchLinux and for Atom I'm using the AUR packaging system (all the packages are locally builded): https://aur.archlinux.org/packages/atom-editor/

As you can read (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=atom-editor), it takes the source archives from github with very few minor patches.

**Comment by lucascosti** [comment] 2016-05-25 00:53
I'm experiencing the same issue. Fedora 22, Atom installed from the mosquito COPR repo:

>$ atom -v
> Atom    : 1.7.3
> Electron: 0.37.7
> Chrome  : 49.0.2623.75
> Node    : 5.10.0

> $ echo $LANG
> en_US.UTF-8

**Comment by 50Wliu** [comment] 2016-05-25 01:45
Anyone who is using the Mosquito COPR repo and is experiencing spell-check difficulties: please report your problem upstream, as that issue does not appear to be caused by Atom.

**Comment by diraimondo** [comment] 2016-05-25 07:39
@50Wliu if this is a problem related to the packaging, this is not only related to the "Moquioto COPR repo". I opened this report and I use the AUR package on Arch Linux. The AUR system is a simple portage-like system that compile the source on the local system.
I'm signaling it to the AUR package authors (see https://aur.archlinux.org/packages/atom-editor/) but it looks strange: as you can see (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=atom-editor) there is nothing of fancy in the way it is compiled. There is a small spell-unrelated patch (https://aur.archlinux.org/cgit/aur.git/tree/package.patch?h=atom-editor).

How are the pre-built released package compiled?

**Comment by 50Wliu** [comment] 2016-05-25 14:33
@diraimondo That's why I didn't close this issue yet, because you're not using the COPR one.  But anyone who's using the COPR has reported that the problem is resolved once they switch to the default ones provided by Atom.

You can see how Atom creates its `.rpm` packages here: https://github.com/atom/atom/blob/21a5ef6d741c3dedec5c71447c5662e1026a77b8/script/mkrpm

**Comment by diraimondo** [comment] 2016-05-25 15:54
@50Wliu Today I did few other tests:
- the 1.7.4 version locally built using the AUR package without the small patch has the same problem with the spell check: the patch is not the cause;
- I've tried to use the prebuilt rpm package by means of the AUR package atom-editor-bin (see https://aur.archlinux.org/packages/atom-editor-bin/) and here the spell check works; the AUR package is still stuck on version 1.6.2 for a problem related to https://github.com/atom/atom/issues/11198;

Looking at the build instructions used by the AUR package and to the RPM one I don't see big differences:
- AUR: `build --build-dir "$srcdir/atom-build"` and `grunt install --build-dir "$srcdir/atom-build" --install-dir "$pkgdir/usr"`;
- RPM: `build` and `grunt mkrpm publish-build --stack --no-color --install-dir /usr`.

Does the compilation used in RPM package make any kind of static linking of the libraries?

**Comment by kriestof** [comment] 2016-06-01 11:07
I had similar problem on Arch. Struggled for few hours with this.

In 1.7.3 from AUR I hadn't spelling. Then I installed ~1.9 beta as described over there https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

Spell checker started working when I set LANG to en_US.utf8. Unfortunately I had set LANG to other language on 1.7.3 so can't tell if it would instantly work. Then I changed again to 1.7.4 from AUR and everything works fine. 

I would give try(from build instructions): ```sudo pacman -S --needed gconf base-devel git nodejs npm libgnome-keyring python2```. Maybe requirements in AUR package are not set correctly. If not I would try to follow carefully all build instructions. But probably you couldn't run 1.7.4 build this way - at last I had some error on Arch. I would recommend trying 1.9 beta then.

**Comment by diraimondo** [comment] 2016-06-02 18:49
I suggest to close this report as I discovered why the Arch Linux package doesn't activate the spell checking. The fixed path used by Atom to search the dictionaries doesn't exist in the created package.

See https://github.com/atom/spell-check/issues/129#issuecomment-223365216

**Closed** 2016-06-02 20:23 UTC
Labels: more-information-needed, needs-reproduction
