### ISSUE TITLE
My atom spell check does not highlight any spelling errors on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by svmotha** [atom/spell-check#150] opened 2016-07-30 15:30 UTC
Tried adding the scope name to the list of grammars as suggested here:

https://discuss.atom.io/t/how-to-enable-spell-checking-for-another-language/4895/3

But I still cannot get it to show me when I misspell anything.

**Comment by 50Wliu** [comment] 2016-07-30 16:08
This is a duplicate of #129 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-30 16:08 UTC
