### ISSUE TITLE
Add to dictionary

### ISSUE THREAD

**Issue by MattDiMu** [atom/spell-check#152] opened 2016-08-03 13:13 UTC
[Feature-Request] This plugin would be even more useful, if it was possible to add custom words to the dictionary (like in MS Word).

For now many of my files look like a Christmas tree with spellcheck enabled, as many special terms are used.

**Comment by 50Wliu** [comment] 2016-08-03 14:32
This is a duplicate of #10 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-03 14:32 UTC
