### ISSUE TITLE
Loaded but not working

### ISSUE THREAD

**Issue by jseto** [atom/spell-check#61] opened 2015-05-12 15:24 UTC
I have spell-check package enabled but it does not appear in the palette and when typing in a document an exception is thrown as you can see in the attached picture.

![screenshot from 2015-05-12 17 19 16](https://cloud.githubusercontent.com/assets/748604/7590938/4898e462-f8cb-11e4-938c-9030a0769683.png)

I'm using Ubuntu 14.04 and Atom 0.198.0

**Comment by lee-dohm** [comment] 2015-05-12 15:41
Duplicate of #52. Please subscribe there for updates.

**Closed by lee-dohm** 2015-05-12 15:41 UTC
