### ISSUE TITLE
Runaway spell check on long document

### ISSUE THREAD

**Issue by lorddoig** [atom/spell-check#53] opened 2015-03-19 14:44 UTC
With spell-check v0.55.0, atom v0.187.0, and OS X 10.10.3.

I've been using AsciiDoc on Atom to write some stuff (but changing to plain text mode makes no difference).  The document exhibiting this problem is around 5000 words long.  I noticed that the red wavy line was lagging tremendously behind my typing, jumping forward a character or two at a time sometimes up to 5 words back!  Then today things degraded further: any kind of typing will spin `Atom Helper` to 50-90% CPU, and `AppleSpell` to near the same -- the fans go to Mach 3, etc.

I had a quick look at the source and am I right in thinking that it dumps the entire document buffer into the spell checker every `::getStoppedChangingDelay` ms when actively editing?  For me, that means checking 5000 words 3.333 times a second, when 99% of the time 4990+ of them are static.  Surely it'd be better to do only the current line/bit that changed since the last run?

Sorry for being all problems and no solutions; I'd have considered doing a PR but CoffeeScript and I aren't friends :worried:

**Comment by Gwnl** [comment] 2015-06-12 09:03
Exactly the same symptoms here with spell-check 0.59, atom 0.209 and OSX 10.10.3.

**Comment by mdlincoln** [comment] 2015-09-15 20:20
Same problem with spell-check 0.59, atom 1.0.11, and OS X 10.10.5

**Comment by JamesGuthrie** [comment] 2015-10-01 13:24
I came across this as well. I have started working on a fix.

**Comment by JamesGuthrie** [comment] 2015-10-01 13:26
Actually it looks like this is a duplicate of #37

**Comment by lee-dohm** [comment] 2015-11-11 19:14
See [this Discuss post](https://discuss.atom.io/t/atomhelper-high-cpu-usage/2553/106?u=leedohm) for more information, including a CPU profile.

**Closed** 2016-01-11 23:33 UTC
Labels: bug, performance
