### ISSUE TITLE
spell check no longer works

### ISSUE THREAD

**Issue by fionahanington** [atom/spell-check#175] opened 2016-11-15 23:34 UTC
Hi there
I have successfully used the Spell Check package on Atom for my restructured text files for several months. It's stopped working though -- I am not sure when, I just noticed it when I was trying to figure out why typos were getting through. 

Details:
platform  - windows 7  professional
grammars - source.asciidoc, source.gfm, text.git-commit, text.plain, text.plain.null-grammar, text.restructuredtext

Use Locales checkbox
enabled 

Locales 
blank

Locales Paths
blank

Known Words
blank

Keybindings  checkbox
enabled

I'd appreciate any pointers on how to fix - thanks
Fiona

**Comment by tofof** [comment] 2016-11-17 02:20
+1 Not working for me either.

Win7
Atom 1.12.3
spell-check 0.68.4
spell-check settings: all default

Grammar of scope I'm in: text.plain.null-grammar (which is in the default list of grammars)

Misspelling a word produces no result.
`ctrl-shift-:` does not bring up a list of suggestions.
`ctrl-:` does not correct a misspelled word.
`Packages > spell-check > toggle` does nothing.

**Comment by fionahanington** [comment] 2016-11-17 19:24
Hi tofof

I solved this problem myself by installing the Hunspell dictionary and then pointing to it within my spell check package's  Locale Paths field 

I don't know why this was suddenly required, as I had a working spell-check before. Nevertheless, this fixed the problem.

**Comment by gncs** [comment] 2017-01-17 13:58
Thank you for your input @fionahanington! I installed `hunspell` and `hunspell-en` on my linux machine and put `/bin/hunspell` for `Locale Paths` but it still does not do anything. This appears to be a problem multiple people are experiencing...

**Comment by gncs** [comment] 2017-01-22 16:54
@fionahanington I think I miss understood your comment. I now added `/usr/share/myspell` to `Locale Paths` and now it works for me, too. :)

**Comment by vysokyj** [comment] 2017-04-08 11:43
I try almost everything and it looks like Locale Paths is ignored on Mac OS.

**Comment by mrunkel** [comment] 2017-04-20 16:50
I'm having the same problem as @vysokyj and @tofof on OS X with Atom v1.60

Spell checking doesn't work for me either.  I have an error about deprecation.

<img width="855" alt="screenshot 2017-04-20 18 47 06" src="https://cloud.githubusercontent.com/assets/3205232/25242417/d50608f0-25f9-11e7-99a5-2bd91c4c3447.png">

Since the stack dump doesn't show what package it's talking about, I don't know if it's related, but since the other issues seem to be around Locale, this is suspicious.

In the console log I have:
`/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:680 

'atom-beautify.yaml.padding' could not set the default. Attempted default: undefined; Schema: {"type":"integer","default":null,"minimum":0,"description":"The amount of padding to add next to each line. (Supported by align-yaml)","title":"Padding","beautifiers":["align-yaml"],"key":"padding","language":{"name":"YAML","namespace":"yaml"}}`

**Comment by the-j0k3r** [comment] 2017-09-01 13:35
> Console shows:
> 
>     spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.
> 
> Win7
> Atom 1.12.3
> spell-check 0.68.4
> spell-check settings: all default
> 
> Grammar of scope I'm in: text.plain.null-grammar (which is in the default list of grammars)
> 
> Misspelling a word produces no result.
> ctrl-shift-: does not bring up a list of suggestions.
> ctrl-: does not correct a misspelled word.
> Packages > spell-check > toggle does nothing.
> 
> C:\Users\<myusername>\AppData\Local\atom\app-.12.3\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries has en_US.dic and en_US.aff files in it.

same as you but with exception of mine are

windows 10 1703, 15603.540
Atom 1.19.5 x64bit
spell-check 0.71.4

your last part

> C:\Users\<myusername>\AppData\Local\atom\app-.12.3\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries has en_US.dic and en_US.aff files in it.

for me doesnt even exist. its

C:\Users\username\AppData\Local\atom\app-1.19.5\resources\app\node_modules\spellchecker\vendor\hunspell_dictionaries,
it has same file inside, 

:(

**Comment by the-j0k3r** [comment] 2017-09-19 07:51
```
Atom 1.20.0 
Windows 10 1703, 15603.608
spell-check 0.72.1
spell-check settings: all default
```

Still broken and no-one associated with project has a single useful or any feedback  on the issue? @smashwilson or @samlambert is there anything to add here?

**Comment by the-j0k3r** [comment] 2017-09-22 08:36
Something changed.

I added Firefox beta 56 and suddenly the Spell Checker came alive. The system previously only had Edge/IE despite Firefox being my preferred browser.

The reason why Firefox would trigger this escapes me, nothing I had done previously ever worked to fix this issue. Its possible its actually a fluke, but since NOTHING changed except that, makes me wonder.

Hope this helps someone or the devs.

**Comment by rsese** [comment] 2018-09-17 06:51
Circling back to this one, it looks like a few folks describe how they got spell check to start working for them.  Since the original author is also past the reported problem, we're going to close this particular issue but folks still having a reproducible problem in the latest versions of Atom can open a new issue with the template filled out and we can take a look.

**Closed by rsese** 2018-09-17 06:51 UTC
