### ISSUE TITLE
Enable check-spelling only out of blocks of code in markdown.

### ISSUE THREAD

**Issue by gustawdaniel** [atom/spell-check#207] opened 2017-05-17 08:21 UTC
### Description

I looking for option of enable check-spelling out of blocks of code and disable it inside of text contained in "```".

**Expected behavior:**

For example I have the following text (in markdown syntax):

```
Some text that should be corrected

\```
Block of code without slashed, but there spell-check should be disabled
\```

There spell checking should be enabled again...
```

**Actual behavior:** [What actually happens]

Now if spell-check is enable, then I see warning in block of code in markdown files.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

```
atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

### Additional Information

I would like to help code it, but I know only js, and there is coffe script, so I do not have any experience in this.

**Comment by 50Wliu** [comment] 2017-05-17 16:51
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
***
Also, Coffeescript is very similar to JavaScript.  If you're familiar with JavaScript, it shouldn't take too long for you to get started with Coffeescript.

**Closed by 50Wliu** 2017-05-17 16:51 UTC

**Comment by SimonAkers** [comment] 2022-09-12 22:27
Since I had to do some digging to figure out how to use the tools that are considered the solution, here is what worked for me to disable spell checking in Markdown code blocks (triple backticks) and raw text (single backticks):

1. Open Atom
2. Navigate to the spell checker settings at `File -> Settings -> Packages -> spell-check`
3. In the `Exluded Scopes` field, put `markup.code.gfm, markup.raw.gfm`
4. Done
