### ISSUE TITLE
Ignore spell-check in code chunks

### ISSUE THREAD

**Issue by tgrrr** [atom/spell-check#312] opened 2019-07-22 04:26 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Add option to ignore spell-check within code-blocks

### Steps to Reproduce

1. Create markdown document
2. Add codeblock with 

```js
// code goes here
```

**Expected behavior:**

Spell-check ignores those words

**Actual behavior:**

Spell-check highlights words in code-block

**Reproduces how often:**

100%

### Versions

spell-check 0.74.5
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 3.6.4
git 2.21.0

Mac Mojave 10.14.5

### Additional Information

I understand that if the language is loaded in atom (ie. language-latex), then that _should_ allow it to be ignored. However, there should be an option to ignore this without loading other language packs.

**Comment by rsese** [comment] 2019-07-26 23:50
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/spell-check/issues/2 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-26 23:50 UTC
