### ISSUE TITLE
The package spell-check cannot load the system dictionary for en_US.

### ISSUE THREAD

**Issue by Spid0r** [atom/spell-check#289] opened 2018-12-23 11:12 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
comes up a warning when i start Atom.
"The package spell-check cannot load the system dictionary for en_US. See the settings for ways of changing the languages used, resolving missing dictionaries, or hiding this warning."
2. [Second Step]
somehow it disables all my autofill thingys.
3. [and so on...]

**Expected behavior:** [What you expect to happen]
i expect the autofill thingys to work.
**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-12-27 22:02
Thanks for contributing!

This is a duplicate of https://github.com/atom/spell-check/issues/253, see for example the suggestions in https://github.com/atom/spell-check/issues/253#issuecomment-386698859 for the operating system you're using.  Also, for future issues, please fill out the issue template as much as possible, the information is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-12-27 22:02 UTC
