### ISSUE TITLE
Cannot load the system dictionary for tr_TR. Checked the following paths for dictionary files:

### ISSUE THREAD

**Issue by RAHMANINkolesi** [atom/spell-check#256] opened 2018-05-10 17:34 UTC
Cannot load the system dictionary for tr_TR. Checked the following paths for dictionary files:

/usr/share/hunspell
/usr/share/myspell
/usr/share/myspell/dicts
/snap/atom/150/usr/share/atom/resources/app.asar.unpacked/node_modules/spellchecker/vendor/hunspell_dictionaries

I am using Linux x64 - Ubuntu 18.04(updated from 16.04)

**Comment by rsese** [comment] 2018-05-10 20:02
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/spell-check/issues/253 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-10 20:02 UTC
