### ISSUE TITLE
All words in sentences containing "it's" treated as misspelled

### ISSUE THREAD

**Issue by surdu** [atom/spell-check#315] opened 2019-09-03 21:05 UTC
### Prerequisites

- [X] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
- [X] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
- [X] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
- [X] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
- [X] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

In an `.md` file, if you have a sentence containing `it's`, all words in that sentence will be treated as misspelled.

<img width="709" alt="Screenshot 2019-09-03 at 23 55 15" src="https://user-images.githubusercontent.com/11520795/64207918-53f57900-cea6-11e9-9d62-57f79d381a3d.png">

Note that the sentence must end in period.

**Reproduces how often:**

Most of the times... For example, the following triggeres the problem:
```
There is nothing wrong with it's nowadays.
```
But the next one does not:

```
There is nothing wrong with it's now.
```

### Versions

```
$ atom-beta --version
Atom    : 1.41.0-beta1
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
$ apm-beta --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0-beta1
python 2.7.10
git 2.20.1
```

```
MacOS 10.14.6 (18G87)
```

**Comment by rsese** [comment] 2019-09-03 23:36
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/spell-check/issues/281 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-03 23:36 UTC
