### ISSUE TITLE
I keep getting error: "Uncaught TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by NathanDoesMuch** [atom/spell-check#131] opened 2016-04-23 15:45 UTC
[Enter steps to reproduce below:]

1. Just try to toggle spellchecker

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Home
**Thrown From**: [spell-check](https://github.com/atom/spell-check) package, v0.67.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\Nathan\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:43

TypeError: Cannot read property 'id' of undefined
    at Object.module.exports.toggle (C:\Users\Nathan\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:43:54)
    at atom-workspace.commandSubscription.atom.commands.add.spell-check:toggle (C:\Users\Nathan\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:13:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Nathan\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Nathan\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Nathan\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Nathan\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\Nathan\AppData\Local\atom\app-1.7.2\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
  3x -4:38 spell-check:toggle (atom-text-editor.editor.is-focused)
     -4:14.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:45.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:13 spell-check:toggle (a.)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "linter-shellcheck"
    ],
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  },
  "spell-check": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-04-23 15:49
Closing as a duplicate of #130 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-23 15:49 UTC
