### ISSUE TITLE
Spanish support and other languages

### ISSUE THREAD

**Issue by faustinoaq** [atom/spell-check#83] opened 2015-09-16 12:40 UTC
I am using Kubuntu 15.04 and Atom 1.0.11
I write in spanish and I do the following:

1. Download spanish dictionaries from `https://github.com/sbosio/rla-es/tree/master/source-code/hispalabras-0.1/hispalabras`
2. Go to `/usr/share/atom/resources/app.asar.unpacked/node_modules/spell-check/node_modules/spellchecker/vendor/hunspell_dictionaries
`
3. Backup and Replace `es_ES.aff → en_US.aff` and `es_ES.dic → en_US.dic`
4. Then `spell-check` was cheated and work with spanish.
5. This method can work with others languages only change its name to `en_US`

I can see many issues about this (#11). Meanwhile I think that we can develop a plugin (and after merge with atom) that download all dictionaries in the location at point **2** and in the setting view or `config.cson`, atom might allow change the language of `spell-check` and also allow add new words like Microsoft Word® "Add to dictionary"

Other question, In the future, Could Atom interface be translated to other languages?, I would help to translate it. I can see something here "[Redering improvements](http://blog.atom.io/2015/06/24/rendering-improvements.html)"

**Comment by mnquintana** [comment] 2015-09-16 13:01
Thanks for the suggestions! This looks like a duplicate of https://github.com/atom/spell-check/issues/11 and https://github.com/atom/spell-check/issues/21 - closing this out in favor of those issues.

As for translations, you might want to follow https://github.com/atom/atom/issues/3103.

**Closed by mnquintana** 2015-09-16 13:01 UTC

**Comment by alexcarrascob** [comment] 2017-06-17 02:31
How can I translate Atom in Spanish on Windows 10? Does anyone knows? Thanks!
