### ISSUE TITLE
Adding words to known words list in spell check does not get rid of the red underline of the word

### ISSUE THREAD

**Issue by doliver3** [atom/spell-check#217] opened 2017-07-01 02:24 UTC
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Create a new document
2. Type the name socialsurf.zone a red underline will appear under it
3. In spell check plugin preferences check off the checkbox to add known words and restart Atom and reopen the new document created in #1
4. Right-click on socialsurg.zone and choose "Add to Known Words' from the context menu
5. Just in case it is an issue requiring restart, restart Atom and reopen the document again.

**Expected behavior:** [What you expect to happen]
The red underline should disappear after the word is added to the known words

**Actual behavior:** [What actually happens]
The red underline does not disappear. The word is still marked as unknown by the spell checker.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time

### Versions
~$ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
~$ apm -version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0

Mac OS Sierra 10.12.5

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-07-03 21:52
Thanks for taking the time to contribute!

I think this looks like a duplicate of https://github.com/atom/spell-check/issues/202, i.e. if I add `socialsurf, zone` to known words, then `socialsurf,zone` is no longer identified as mis-spelled. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-03 21:52 UTC
