### ISSUE TITLE
Check spelling in git commit message

### ISSUE THREAD

**Issue by rugk** [atom/spell-check#301] opened 2019-04-02 19:32 UTC
It would be great if this could also integrate into Atom's git integration, so we can get spell checking when writing git commits…

After all, there, they are even more embarrasing than in the code… :stuck_out_tongue_winking_eye:

**Comment by rsese** [comment] 2019-04-03 01:31
Thanks for contributing!

I believe you're talking about the GitHub package's commit text box?  If so, this is a duplicate of https://github.com/atom/github/issues/1071 and you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-03 01:31 UTC
