### ISSUE TITLE
Default system dictionary not honored under debian.

### ISSUE THREAD

**Issue by emazep** [atom/spell-check#44] opened 2014-12-29 14:44 UTC
The readme says: "This package will use the dictionary set by the system", but under debian this is not the case. Debian default wordlist is the one pointed by /usr/share/dict/words, which this package seems to ignore.

**Comment by benplumley** [comment] 2015-01-09 13:03
Confirming on Windows 8.1, system language is UK English but the package uses American English.

**Comment by winnieXY** [comment] 2015-03-06 14:18
Confirming on Debian Unstable. System language is german, but atom uses the preinstalled american english language files. Please add a possibility to switch the language inside atom or make atom honor the system settings, as this is a show-stopper to write huge documents (e.g. a thesis in latex) with atom.

**Comment by gordon1992** [comment] 2015-03-12 18:42
Confirming on OS X Yosemite. https://www.dropbox.com/s/o1f4d6dnh8z0hiu/Screenshot%202015-03-12%2018.42.19.png?dl=0

**Comment by timbru31** [comment] 2015-03-23 11:15
setting OS X 10.10.2 to "automatic by language" will ignore this setting, too.
I have a native German md file and it's checked in English.

**Comment by Gwnl** [comment] 2015-04-10 11:18
Same here with OSX 10.10.3 and the latest packages. The system preference in Keyboard/Text/Spelling is not used. I also tried with a clean `~/.atom` directory but that didn't help.

**Comment by winnieXY** [comment] 2015-04-23 12:13
Updating to the lates git version changes the behaviour of spell-check on debian. Up to now it was possible to put the german .aff and .dic files in /usr/share and use them. but they're not longer honored. Replacing the .aff and .dic file in ~/.atom has no effect at all and my system settings are also not honored. 

Please give at least a small howto force to use one language until this bug is properly fixed. German language correction is crucial for me, as I'm writing currently my PhD thesis with atom - so please give a hint how to change it the dictionary the hard way now.

**Comment by danielbayley** [comment] 2015-07-24 00:01
Same for me on OS X Yosemite 10.10.4.

> Please add a possibility to switch the language inside atom or make atom honor the system settings, as this is a show-stopper to write huge documents (e.g. a thesis in latex) with atom.

Honouring the system setting would definately be preferable.

**Comment by david-guenault** [comment] 2015-09-02 11:11
+1 since most of us (i guess) alos use atom to write documentations (ex : markdown) , it should be fixed and we should be able to choose the language (not only on a default basis but also in a per document basis).

**Comment by getreu** [comment] 2015-09-08 05:29
Atom has excellent support for writing documentations with Asciidoctor. Here also selecting other languages for spell-checking would be extremely useful.

**Comment by hollandjg** [comment] 2015-09-29 10:05
This seems to be the same problem as https://github.com/atom/node-spellchecker/issues/15 and https://github.com/atom/spell-check/issues/11

**Comment by MAccadia** [comment] 2015-11-07 22:27
Any news on this issue ? Any workaround ?
I'm using Atom 1.0.15 on Ubuntu with `LANG` set to fr_FR.

**Comment by paulcbetts** [comment] 2015-11-07 22:47
Dupe of #11

**Comment by dmoonfire** [comment] 2019-08-29 19:03
I believe this has been resolved through various changes related to the system and locale-based checking in the last few years. Closing the issue; feel free to re-open if further conversation is needed.

**Closed by dmoonfire** 2019-08-29 19:03 UTC
Labels: bug
