### ISSUE TITLE
(1.12.6) Spell-Check Package No Longer Working After Toggle

### ISSUE THREAD

**Issue by wvbraun** [atom/spell-check#177] opened 2016-11-30 23:17 UTC
The spell-check package is no longer checking spelling for any file type. 

Spell-Check was working up until a few days ago. It stopped working after toggling the spell-check package (toggling does nothing now). 

Grammer: source.asciidoc, source.gfm, text.git-commit, text.plain, text.plain.null-grammar

I have tried ctrl-shit-p -> Editor: Log Cursor Scope (no)
I have tried moving ~/.atom/storage to ~/.atom/storage-backup (no)
I have tried uninstalling the spell-check package (Error: cannot find module)
I have tried reinstalling atom (no)

Any other suggestions?

Any other information needed?

**Comment by 50Wliu** [comment] 2016-12-01 01:12
Have you tried moving the entire `~/.atom` folder?

**Comment by wvbraun** [comment] 2016-12-02 18:02
@50Wliu  - I just tried moving the ~/.atom folder and spell-check is still not working, the good news is that it removed all installed packages :/.

This seems to be an ongoing issue that has been occurring for years, surely there must be a solution?

**Comment by robinweiss89** [comment] 2016-12-05 05:10
I'm experiencing the same problem. It only works in the untitled editor.

<img width="488" alt="screen shot 2016-12-05 at 13 09 58" src="https://cloud.githubusercontent.com/assets/12613705/20874373/26fd0100-baec-11e6-8c44-65b6974e48cc.png">

**Comment by tinyinstance** [comment] 2016-12-05 07:57
Same problem here too

**Comment by lee-dohm** [comment] 2016-12-23 22:39
@wvbraun What grammar is active when you run into this problem?

**Comment by JIMMMY0** [comment] 2016-12-28 11:06
same problem here, spell-check package does nothing ...

**Comment by wyhitcs** [comment] 2016-12-30 00:21
I'm writing markdown and spell-check does not work, when I copy my text to a new "untitled" file, it works @lee-dohm

**Comment by lee-dohm** [comment] 2016-12-30 17:55
@wyhitcs @JIMMMY0 can you post a screenshot of the status bar when spell check is not working? If it says something other than "GitHub Markdown", then this is not a bug with spell-check.

**Comment by JIMMMY0** [comment] 2016-12-30 18:55
@lee-dohm   please see the attached picture, hope you could help me. I've tried different methods but it doesn't work at all no matter it is plain text or markdown github.  In the grammar settings, I have included them all.   Even I tried linter spell, it still doesn't work.
![image](https://cloud.githubusercontent.com/assets/21951699/21570677/50c02802-cf03-11e6-82b6-ea11d33a0825.png)
![image](https://cloud.githubusercontent.com/assets/21951699/21570789/48439f0a-cf04-11e6-91fb-8bb6aac8b9a9.png)

**Comment by 50Wliu** [comment] 2016-12-31 00:08
@JIMMMY0 First of all, is the issue still present in safe mode (`atom --safe`)?  If it is, can you please open the developer tools (ctrl-alt-i or ctrl-shift-i, depending on your version of Atom) and provide a screenshot of the "Console" tab?

**Comment by JIMMMY0** [comment] 2016-12-31 11:27
@50Wliu   It says it cannot find en-US dictionary.  Is there any solution for this?  By the way, Happy new year to you all!
![image](https://cloud.githubusercontent.com/assets/21951699/21577246/31dec7d6-cf8f-11e6-8b2f-6bf33f2df814.png)

**Comment by 50Wliu** [comment] 2016-12-31 16:22
Ok, it looks like you're experiencing #162.  Try downloading the files listed in [this comment](https://github.com/atom/spell-check/issues/162#issuecomment-254812332) or the one below it, move them to a folder, and then point spell-check to that folder in the Settings View.

I'm going to guess that this whole issue is actually #162 so I'm closing this in favor of that one.

**Closed by 50Wliu** 2016-12-31 16:22 UTC
Labels: more-information-needed

**Comment by wvbraun** [comment] 2017-01-03 18:51
Following the suggestions from #162 worked!

@50Wliu I agree, I think it is related to #162. I downloaded the files and updated my spell-check package "Locale Paths" to point to the location of the files (WIN). 
If anyone else has this issue, try this:
1. Download the [Hunspell's dictionary](https://sourceforge.net/projects/hunspell/files/Spelling%20dictionaries/en_US/) (find your correct region)
2. cd to that location; unzip 'en_US.zip'
3. mkdir ~/AppData/Roaming/Atom/Spelling; mv 'en_US' ~/AppData/Roaming/Atom/Spelling/
4. Go to the Settings view for the spell-check package, and paste the full path to that folder in the Locale Paths field.

@lee-dohm the grammar were source.asciidoc, source.gfm, text.git-commit, text.plain, text.plain.null-grammar
