### ISSUE TITLE
Alternate Apostrophe shows as misspelled.

### ISSUE THREAD

**Issue by jdgwf** [atom/spell-check#280] opened 2018-11-09 21:32 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When a standard Ascii 39 (') apostrophe is used, contraction words are marked properly spelled. However, when I use an alternate apostrope Ascii 146 (’) the word is marked misspelled.

I write markdown with standard Ascii39 then change the written pages with smart-quotes-plus (https://atom.io/packages/smart-quotes-plus) for export to epub and mobis

I'd like for the Ascii146 to be treated like an Ascii39 by the spell checker.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/316824/48289194-385f4480-e434-11e8-98a8-b91be499baeb.png)
![image](https://user-images.githubusercontent.com/316824/48289207-401ee900-e434-11e8-9100-9e58a9302652.png)

**Expected behavior:** I'd expect contractions to be marked properly spelled with both characters

**Actual behavior:** First part of contraction is marked as a separate word then counted as a misspelled word

**Reproduces how often:** 100% with alternate apostrophe

**Comment by dmoonfire** [comment] 2018-11-26 22:03
What operating system? The reason I ask is because Mac and Windows 10 both use a different spell-checking than the others.

**Comment by jdgwf** [comment] 2018-11-26 22:06
My apologies for not specifying this. It's Linux, 
Specifically Ubuntu Linux 18.10, but it's doing the same behavior in 18.04 and 16.04

**Comment by jdgwf** [comment] 2019-02-17 05:53
It looks like Linux (at least Ubuntu) is using the hunspell dictionaries in the /usr/share/hunspell 
Would it be possible to patch spell-check to replace the character before comparison and still keep its speed?

**Comment by dmoonfire** [comment] 2020-09-04 01:01
Looking into this, but I don't think I can figure out how to do this easily or quickly. Because we don't do word splitting, we would have to do a replace on the entire buffer before passing it over to Hunspell. So for large documents, this would effectively double the usage and probably wouldn't be very fast either.

There are some discussions about that which pretty much say the only approach is to do the S/R.

- https://www.mobileread.com/forums/showthread.php?p=3325010
- https://github.com/en-wl/wordlist/issues/122

I'm going to close this issue as not solvable with Atom as the problem is integral to Hunspell which doesn't support it.

**Closed by dmoonfire** 2020-09-04 01:01 UTC
