### ISSUE TITLE
causes issues with opening and viewing large files (>18 Mb)

### ISSUE THREAD

**Issue by zeff013** [atom/spell-check#260] opened 2018-06-15 10:55 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

opening large log files (Atlassian Jira Software server in question) with spellcheck enable causes atom's slowness and freeze after some time.

### Steps to Reproduce

1. open standard Atlassian Jira Software log file and note the delay/slowness.
2. search for something, use "find next" and/or scroll back and forth for some time.
3. atom freezes.

**Expected behaviour:** [What you expect to happen]

Either automatically suggest to turn off spelling due to too many errors found in the document
or fix spelling to work correctly without causing slowness and freezing.

Ideas for improvement:
1. avoid spell checking whole document immediately on file open and rather do it for visible text only.
2. avoid spell checking visible document, while document is being scrolled.

**Actual behavior:** [What actually happens]

atom freezes completely.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.27.2
spell-check : 0.73.4

### Additional Information

**Comment by rsese** [comment] 2018-07-12 20:46
Thanks for opening a new issue for this @zeff013 - just to clarify, how large is the log file?  Also, what operating system are you running?  I think this could be close enough to be a duplicate of https://github.com/atom/spell-check/issues/37 since I'm assuming the log file is opened as Plain Text.

**Comment by rsese** [comment] 2018-07-12 20:46
> just to clarify, how large is the log file?

lol sorry just saw this in your issue title :v:

**Closed** 2018-10-04 12:43 UTC
Labels: more-information-needed

**Comment by Arcanemagus** [comment] 2018-10-04 16:07
For reference, `spell-check` is now disabled on files larger than `LARGE_FILE_SIZE` (currently 2 MiB) as of #265.
