### ISSUE TITLE
Locale Paths not working on MacOS.

### ISSUE THREAD

**Issue by vysokyj** [atom/spell-check#196] opened 2017-03-14 11:53 UTC
Locale Paths not working on MacOS.

Settings:
Use Locales: checked
Locales: cs-CZ
Locale Paths: /usr/local/share/hunspell

Hunspell dictionaries:
`ls /usr/local/share/hunspell
cs_CZ.aff cs_CZ.dic en_GB.aff en_GB.dic en_US.aff en_US.dic`

Development console output:
`spell-check:cs-cz Can't load cs-CZ: Cannot find dictionary for cs-CZ.`

**Comment by vysokyj** [comment] 2017-03-16 13:04
System spell checker not working too. I have added my cs_CZ dictionary to my /Library/Spelling directory and NSSpellChecker offers it correctly.


Swift Playground code:

``` swift
import Cocoa
import AppKit

var checker = NSSpellChecker.shared()
checker.availableLanguages
```

Output:

```
["cs_CZ", "en", "en_GB", "en_AU", "en_CA", "en_IN", "en_SG", "en_JP", "da", "de", "es", "fr", "it", "nl", "nb", "pl", "pt_BR", "pt_PT", "fi", "sv", "tr", "ru", "ko", "sk_SK"]
```

**Comment by rsese** [comment] 2017-03-16 21:42
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

But I see that you already posted this question a while ago but there was no followup:

https://discuss.atom.io/t/spell-check-i-cant-get-it-to-work-at-all/28708/5

Let's go ahead and close this for now but I'll followup in that post since I tried this as well but was having the same problem.   Hopefully someone can help us out in the forum but if it's instead confirmed that it's a bug rather than something we're not doing correctly, we can re-open this issue.

**Closed by rsese** 2017-03-16 21:42 UTC
