### ISSUE TITLE
Spell Checker not working after recent update

### ISSUE THREAD

**Issue by WillNaylor1994** [atom/spell-check#333] opened 2020-05-14 19:33 UTC
Hi! I'm having issues with Atom's spell checker after the most recent updates.

Not sure if this is the right place to post this?

I've been on a few forums trying to fix this, has not worked so far. I haven't tried fully deleting Atom and re-installing, but trying to avoid that.

Prerequisites
 Put an X between the brackets on this line if you have done all of the following:
Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode (X)
Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/ (X)
Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq (X)
Checked that your issue isn't already filed: https://github.com/issues? utf8=✓&q=is%3Aissue+user%3Aatom (X)
Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages (X)
Description

Hi! I'm having issues with Atom's spell checker after the most recent updates.

Not sure if this is the right place to post this?

I've been on a few forums trying to fix this, has not worked so far. I haven't tried fully deleting Atom and re-installing, but trying to avoid that.

I've tried moving storage to storage-backup as one person suggested, still didn't work.

Steps to Reproduce
Tried safe mode, no diference.

Tried various steps from online.

Expected behavior: Spell checker to work

Actual behavior: It doesn't work.

Reproduces how often: I can't get it to work.

Versions

1.46.0 - Windows 10.

Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dmoonfire** [comment] 2020-05-18 06:11
Duplicate of https://github.com/atom/spell-check/issues/328.

**Closed by dmoonfire** 2020-05-18 06:11 UTC
