### ISSUE TITLE
Does not work with child elements unless parent is included. for example "string.quoted.double.java" does not work

### ISSUE THREAD

**Issue by Phara0h** [atom/spell-check#77] opened 2015-07-24 19:10 UTC
Things like "string.quoted.double.java" do not work unless you add "source.java" which will spell check everything in the file like class names and such which you would not want spell checked.

**Comment by izuzak** [comment] 2015-09-13 11:36
I believe this is a duplicate of https://github.com/atom/spell-check/issues/2. Currently -- the package supports only scopes which refer to grammars, not scopes which refer to parts of grammars. I do agree that would be helpful, though.

**Closed by izuzak** 2015-09-13 11:36 UTC
