### ISSUE TITLE
Not set other language.

### ISSUE THREAD

**Issue by lynxbyorion** [atom/spell-check#65] opened 2015-06-01 20:56 UTC
I am changed system dictionary (OS X, russian) and spell checker worked in other apps. But Atom still checked only English language.

<img src="https://cloud.githubusercontent.com/assets/402369/7922990/47355dfe-08c9-11e5-8401-363296d4c238.png"  width=180> <img src="https://cloud.githubusercontent.com/assets/402369/7922991/476d61fe-08c9-11e5-8f3a-1e347121893c.png"  width=250>

**Comment by 50Wliu** [comment] 2015-06-01 22:28
Duplicate of #11, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-01 22:28 UTC
