### ISSUE TITLE
Spell check in portuguese language

### ISSUE THREAD

**Issue by trprado** [atom/spell-check#62] opened 2015-05-26 20:16 UTC
Atom is not correctly using system spell check in portuguese language.

![spell-check-portuguese](https://cloud.githubusercontent.com/assets/4511706/7822289/f4a7084c-03ca-11e5-83b0-9f600352626f.png)

**Comment by lee-dohm** [comment] 2015-05-26 23:37
This is a duplicate of #11. Please subscribe there for updates.

**Closed by lee-dohm** 2015-05-26 23:37 UTC
