### ISSUE TITLE
Wrong dictionary on Mac OS X?

### ISSUE THREAD

**Issue by mathie** [atom/spell-check#50] opened 2015-02-25 18:53 UTC
I finally got around to looking into why Atom's spell checker is complaining about my anglicised english. From the documentation, I checked my system dictionary. Spelling was set to "Automatic by Language", but I've now changed it to "British English" (and restarted everything for good measure), and it's still not liking my spelling of "favourite":

![keyboard_and_my-favourite-interview-question_markdown_-__users_mathie_development_personal_mathie_github_io_-_atom](https://cloud.githubusercontent.com/assets/438/6377899/71ac36b6-bd1f-11e4-8435-fe516987fce1.png)

Is there something else I need to change for it to accept my outdated spelling? :smile:

**Comment by lee-dohm** [comment] 2015-02-26 00:59
This is a duplicate of #11 (though the title of that bug doesn't make it obvious). Please subscribe to that issue for updates.

**Closed by lee-dohm** 2015-02-26 00:59 UTC
