### ISSUE TITLE
Enabling spell-checker on specific scope while excluding other scopes

### ISSUE THREAD

**Issue by nmiculinic** [atom/spell-check#133] opened 2016-04-25 11:30 UTC
Situation is like this:
I am writing LaTeX file, and file scope is ```text.tex.latex```

Some parts have additional scope, such as: ```string.other.math.tex``` or ```support.function.general.tex```, ```support.function.section.latex``` where spell checker would only interfere with my workflow.

Thus I'd like to set up spell checker to only work on pure ```text.tex.latex``` and ignore everything wrritten in scopes containing ```string.othre.math.tex``` and similar

How would I do that in spell-check package? 

P.S.
If I am thinking correctly, comments in python and similar language have their own special scope for highlighting? Thus it may be possible to enable spell check in comments only, without bloating the code with unhelpful spell checks.

**Comment by lee-dohm** [comment] 2016-04-28 23:44
This is a duplicate of #118. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-04-28 23:44 UTC
Labels: duplicate
